server:
  servlet:
    encoding:
      charset: utf-8
      force: true
  port: 8012
spring:
  application:
    name: user-service # Eureka 환경에서 통신할 고유id 지정
  config:
    import:
      secret.yml
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true  # SQL을 보기 좋게 포맷후 출력
  data:
    redis:
      host: localhost
#      host: redis
      port: 6379
logging:
  level:
    '[org.hibernate.type]': TRACE
eureka:
  instance:
    prefer-ip-address: true # 서비스의 호스트이름이 아닌 ip주소를 유레카서버에 등록 할지 여부
    # 배포환경에서 DNS가 존재하면 할당받은 호스트이름을 Eureka서버에 등록하면 되지만 컨테이너 기반의 배포환경일 경우
    # 컨테이너가 DNS 엔트리가 없는 임의의 호스트이름이 부여되기 때문에 false로 설정시 유레카서버가 해당 서비스의 호스트 이름위치를 정상적으로 얻지 못함
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
