spring:
  datasource: # 데이터 소스(데이터베이스 연결 설정) 구성
    url: jdbc:mysql://localhost:3305/ninishop # local utl
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  mail:
    host: smtp.gmail.com
    port: 587
    username: skrskr9403@gmail.com
    password: ovddibeiwobmrvsx
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    auth-code-expiration-millis: 1800000  # 30 * 60 * 1000 == 30분
secret:
  AES256: "xak47grandfather"