server:
  port: 8761

spring:
  application:
    name: eureka-server

eureka:
  client:
    register-with-eureka: false # 현재 서비스를 eureka server에 등록 여부
    fetch-registry: false # 다른 서비스들의 정보를 eureka server로 부터 받아서 로컬메모리에 캐싱할지 여부
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ # Eureka Server URL지정 Eureka API 요청용 URL

  server:
    # 서버가 요청을 받기 전 대기할 초기 시간(ms)
    # default 5분 : 실무에서는 보통 모든 서비스가 등록 되길 기다리기 위해 5분 후 정보를 공유
    # 개인 프로젝트인 만큼 빠른 등록을 위해 5ms로 설정
    wait-time-in-ms-when-sync-empty: 5

management:
  endpoints:
    web:
      exposure:
        include: "*" # Spring Actuator의 어떤 API를 사용할 지 지정하는 설정, * : 우선 모든 API사용